### ISSUE TITLE
Web interface become unaccessible after some time

### ISSUE THREAD

**Issue by mgalardini** [HarrisonSteel/ChiBio#13]
Hi,

we have noticed that the chibio web interface (the one served at port 5000) often becomes unaccessible after some time that an experiment has been running. The data keeps being collected and the other plan9 web interface still works. The only solution is to shut down the webserver, turn it on again and restart the experiment.

So far we have been unable to diagnose the problem, even though we have made changes that in theory would allow us to see error messages. We have changed the `cb.sh` file so that the following options are added to `gunicorn`: ` --capture-output --log-level debug --timeout 0 --access-logfile - `. The timeout argument was necessary so that the server would not crash (thus ending the data collection) when the web interface would stop responding. We have also modified the `app.py` file so that instead of `print` we use the `logging` module:

```
application = Flask(__name__)
application.config['SEND_FILE_MAX_AGE_DEFAULT'] = 0 #Try this https://stackoverflow.com/questions/23112316/using-flask-how-do-i-modify-the-cache-control-header-for-all-output/23115561#23115561

import logging
gunicorn_logger = logging.getLogger('gunicorn.error')
application.logger.handlers = gunicorn_logger.handlers
application.logger.setLevel(gunicorn_logger.level)
``` 

and then changed all instances of `print` with `application.logger.info`, `application.logger.debug`, `application.logger.warning` and so on... Unfortunately nothing looks out of place, we see `GET` and `POST` requests while the web interface is on but nothing that would signal problems leading to the interface being unresponsive.

**My question is then:** is this a known problem and if so, is there a way to mitigate it? Alternatively, would there be a way to "reboot" the web interface without stopping an experiment? In general I think that if there was a way to separate the web interface from the control of the devices and data collection the whole thing would be more robust. Not clear to me how easy that would be though.

Best,
Marco

**Comment by HarrisonSteel** [comment]
Hello Marco,

Very interesting. We _did_ have issues like this ages ago which were to do with the browser basically storing _all_ of the data coming from the web server back-end, and eventually running out of memory (on the host PC). Have you looked at your browser memory usage to check if this is getting out of hand?  

However, as I said this _was_ a problem; I fixed it and we have not had this issue for years so I assume it was all sorted out unless some recent software update has re-created it.

In practice we have often run the devices for a month or more without issue. How long _are_ your experiments that you are seeing this? If you are running for shorter times, adn have all the standard software, then the most likely explanation might be something idiosyncratic with your host PC setup. Have you tried connecting to a different computer and see if the issue persists?

Harrison

**Comment by mgalardini** [comment]
Thanks for your prompt reply; I think there's been a misunderstanding. The problem (as far as I can tell) does not lie with the host PC (meaning the PC that connects to the Chi.bio computer); we have the chibio controller attached via ethernet to our local network and we see the issue from multiple PCs trying to access the web interface. The problem usually presents after a few hours (<24) of operation.

Are you basically suggesting we should have the chi.bio board attached to a single PC via the USB connector instead of a local network?

**Comment by HarrisonSteel** [comment]
I wasnt suggesting that in particular, but given what you said it seems like that might be a good option. In our case (and for most users) connected via USb to a specifc computer works perfectly and doesn't crash. I know there is some capability in the code to have it on ethernet but this was implemented by someone else (not me) and is not used in our lab, so I can't say that I have ironed out all the bugs in it! 

I am not sure then what the ethernet issue would be. I guess you could have a google around for other users of the beaglebone that are trying to deliver a web server interface over ethernet and see if there are any common issues that might be relevant.

**Comment by mgalardini** [comment]
Hi again, I'm happy to report that the problem might have indeed been the use of the ethernet port instead of the USB connection. We have run a dummy experiment for a few days and the whole system is much more responsive and the web interface does not freeze. Perhaps something to point out in the documentation? Granted, we did not follow it, but maybe an explicit warning to not try to be clever would help other adventurous souls

**Comment by HarrisonSteel** [comment]
Glad it worked :)
